### ISSUE TITLE
Add donate button

### ISSUE THREAD

**Issue by jessbeutler** [osmus/maproulette-charter-project#10]
A donation page has been set up for MapRoulette: https://openstreetmap.app.neoncrm.com/forms/maproulette

I suggest that a link is added to the MapRoulette website as well as other relevant spots (i.e. OSM wiki).

**Comment by mvexel** [comment]
We would also need to shut down the liberapay account https://liberapay.com/mvexel/donate

**Comment by jessbeutler** [comment]
If you want to keep up the liberapay account, we could also consider just switching where the donations go. Let me know! I wouldn't want to disrupt donations for the sake of consolidation.

**Comment by mvexel** [comment]
we currently have a grand total of $1.21 a month coming in on this so I am not overly concerned about disruption.
