### ISSUE TITLE
Plug-in to OSM US Communications Channels

### ISSUE THREAD

**Issue by jessbeutler** [osmus/maproulette-charter-project#3]
OpenStreetMap US has several places for you to communicate both internally with our team and externally with the broader community. We’re happy to assist with developing a communications plan later on to support with project outreach, but for now, here’s where to start:

- [x]  OSM US Slack - create an MapRoulette channel for public communications
- [x]  OSM US Slack - join the private charter project channel
- [ ]  OSM US Newsletter: If you have not already, sign up for the newsletter [here](https://openstreetmap.app.neoncrm.com/np/clients/openstreetmap/subscribe.jsp?subscription=3&).
- [ ]  Share social media handles with OSM US team

**Comment by mvexel** [comment]
main social media is mastodon: https://en.osm.town/@MapRoulette 
twitter is secondary, https://twitter.com/maproulette
We have a blog at blog.maproulette.org
did you want *access* to these as well?

**Comment by jessbeutler** [comment]
Nope! Don't need access unless you ever ask us to post for you. Just wanted to make sure Nellie had these for social media following/mentions
