### ISSUE TITLE
Blog post announcing charter arrangement

### ISSUE THREAD

**Issue by jessbeutler** [osmus/maproulette-charter-project#4]
- [x] Required: OSM US blogpost announcing charter project
- [ ] Optional: additional blog post on personal or project blog

**Comment by mvexel** [comment]
can we repost what's on OSM US to blog.maproulette.org?

**Comment by jake-low** [comment]
OSM US Blog post: https://openstreetmap.us/news/2023/03/MapRoulette_Announcement/

Closing as completed.
