### ISSUE TITLE
Logo exchange & branding guidelines

### ISSUE THREAD

**Issue by jessbeutler** [osmus/maproulette-charter-project#5]
Please add your logo files to the repo, as well as any guidelines. OpenStreetMap US will add our logos as well for MapRoulette's use. 

We also encourage a combo logo, where possible. See an example of the TeachOSM logo below (this is a program, not a charter project but the same concept can be applied):
![TeachOSM_programlogo](https://user-images.githubusercontent.com/36767434/224185665-283da48c-345a-422e-b0cc-824b0ba55cff.png)

**Comment by mvexel** [comment]
@jschwarz2030 is there a png version of the logo somewhere? All I have is these without text:

![maproulette-logo-800](https://github.com/osmus/maproulette-charter-project/assets/120452/2af0e009-125f-47b7-bebb-bfe15b3de400)

![maproulette-logo-1600](https://github.com/osmus/maproulette-charter-project/assets/120452/fd6f377f-baa1-4ec9-bc62-b3cf562f3eb2)

**Comment by jessbeutler** [comment]
Added OpenStreetMap US Branding Guidelines to the wiki in this repo
