### ISSUE TITLE
Adopt and share the OpenStreetMap US Code of Conduct

### ISSUE THREAD

**Issue by jessbeutler** [osmus/maproulette-charter-project#7]
As an OpenStreetMap US Charter Project, you’ve agreed to adopt our [Code of Conduct](https://wiki.openstreetmap.org/wiki/Foundation/Local_Chapters/United_States/Code_of_Conduct_Committee/OSM_US_Code_of_Conduct) for your project. As part of this, you will need to:

- [ ]  Share and review the Code of Conduct among the Advisory Board making sure everyone understands the terms and knows how to report issues.

- [ ]  Add the link to our Code of Conduct to your website, github, OSM wiki, and/or other areas where contributors and users will interact with the project.

**Comment by mvexel** [comment]
asked on Slack that everyone review and acknowledge here or post any questions / concerns.

**Comment by mattmanley** [comment]
Acknowledging that I've read the policy. No questions or concerns.

**Comment by jake-low** [comment]
Completed, see https://github.com/maproulette/maproulette3/pull/2458 and https://github.com/maproulette/maproulette-backend/pull/1151.
