### ISSUE TITLE
Update OSM Wiki pages

### ISSUE THREAD

**Issue by jessbeutler** [osmus/maproulette-charter-project#9]
Update OSM Wiki pages to reflect your charter status:

- [ ]  [MapRoulette page](https://wiki.openstreetmap.org/wiki/MapRoulette)
- [ ]  [OpenStreetMap US](https://wiki.openstreetmap.org/wiki/Foundation/Local_Chapters/United_States#Charter_Projects) page.

**Comment by atiannicelli** [comment]
I'll take this issue.
